<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSCWrQxR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSCWrQxR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSCWrQxR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSCWrQxR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSCWrQxR\App_KernelDevDebugContainer([
    'container.build_hash' => 'SCWrQxR',
    'container.build_id' => '95827a27',
    'container.build_time' => 1754988195,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSCWrQxR');
